### ISSUE TITLE
قطع شدن ارتباط از سرور خارج

### ISSUE THREAD

**Issue by hitcher406** [Azumi67/Rathole_reverseTunnel#1]
سلام و خسته نباشید
تشکر از این اسکریگت خوب و کارآمدتون
من وقتی اجرا میکنم تانل رو به صورت یک به یک با ipv6 tcp
اولش خیلی خوب کار میکنه بعدش گاهی یک روز گاهی دو ساعت سرور خارج قطع میشه با ارور 110
همزمان دو سرور خارج رو به دو سرور ایران تانل کردم (یعنی دو تانل یک به یک جدا از هم) و جالب اینجاست که همزمان قطع میشن!

root@N1:/etc/systemd/system# systemctl status kharej-azumi.service
● kharej-azumi.service - Kharej-Azumi Service
     Loaded: loaded (/etc/systemd/system/kharej-azumi.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-01-08 13:07:49 UTC; 3h 3min ago
   Main PID: 26865 (rathole)
      Tasks: 5 (limit: 4524)
     Memory: 38.8M
        CPU: 13min 28.978s
     CGroup: /system.slice/kharej-azumi.service
             └─26865 /root/rathole/target/debug/rathole /root/rathole/client.toml

Jan 08 16:10:03 N1 rathole[498547]: 2024-01-08T16:10:03.478462Z  WARN handle{service=kharej4}:run: rathole::client: Failed to run the data channel: Failed to connect to ["my ipv6]:443: Connection timed out (os error 110)
Jan 08 16:10:03 N1 rathole[498547]: 2024-01-08T16:10:03.478585Z  WARN handle{service=kharej4}:run: rathole::client: Failed to run the data channel: Failed to connect to ["my ipv6]:443: Connection timed out (os error 110)
Jan 08 16:10:03 N1 rathole[498547]: 2024-01-08T16:10:03.478741Z  WARN handle{service=kharej4}:run: rathole::client: Failed to run the data channel: Failed to connect to ["my ipv6]:443: Connection timed out (os error 110)
Jan 08 16:10:03 N1 rathole[498547]: 2024-01-08T16:10:03.478771Z  WARN handle{service=kharej6}:run: rathole::client: Failed to run the data channel: Failed to connect to ["my ipv6]:443: Connection timed out (os error 110)
Jan 08 16:10:03 N1 rathole[498547]: 2024-01-08T16:10:03.478822Z  WARN handle{service=kharej4}:run: rathole::client: Failed to run the data channel: Failed to connect to ["my ipv6]:443: Connection timed out (os error 110)
Jan 08 16:10:03 N1 rathole[498547]: 2024-01-08T16:10:03.478846Z  WARN handle{service=kharej6}:run: rathole::client: Failed to run the data channel: Failed to connect to ["my ipv6]:443: Connection timed out (os error 110)
Jan 08 16:10:03 N1 rathole[498547]: 2024-01-08T16:10:03.478893Z  WARN handle{service=kharej4}:run: rathole::client: Failed to run the data channel: Failed to connect to ["my ipv6]:443: Connection timed out (os error 110)
Jan 08 16:10:03 N1 rathole[498547]: 2024-01-08T16:10:03.478910Z  WARN handle{service=kharej4}:run: rathole::client: Failed to run the data channel: Failed to connect to ["my ipv6]:443: Connection timed out (os error 110)
Jan 08 16:10:03 N1 rathole[498547]: 2024-01-08T16:10:03.479037Z  WARN handle{service=kharej4}:run: rathole::client: Failed to run the data channel: Failed to connect to ["my ipv6]:443: Connection timed out (os error 110)
Jan 08 16:10:15 N1 rathole[498547]: 2024-01-08T16:10:15.761908Z  WARN handle{service=kharej4}:run: rathole::client: Failed to run the data channel: Failed to connect to ["my ipv6]:443: Connection timed out (os error 110)

اینم بگم که با اجرای اسکریپت و ReStart سرویس از داخل اسکریپت روی سرور خارج مشکل موقت حل میشه ولی باز این اتفاق میفته

**Comment by hitcher406** [comment]
اینم بگم که با اجرای اسکریپت و ReStart سرویس از داخل اسکریگت روی سرور خارج مشکل موقت حل میشه ولی باز این اتفاق میفته

**Comment by Azumi67** [comment]
سلام مرسی . نتونسته با سرور شما و با ایپی 6 به خاطر Unreachable بودن ان ، ارتباطی برقرار کنه. 
شما چند کار بکنید. بررسی کنید پورت های دیگه چطوری هستن . ایا اختلالی بر روی ایپی 6 هست ، اگربله ایپی 6 جدیدی بسازید. اگر ریست تایمر را عدد بالایی گذاشتید 1 ساعته کنید. چون 3ساعت بدون مشکل مثل اینکه کار کرده حالا دقیقا معلوم نیست.
ببینید اگر 6to4 انجام دادید اختلال از اون نباشه. اگر native ip هست ، ایپی دیگری بسازید.
اگر تعداد یوزر بالایی دارید بین سرور های محتلف پخش کنید
از optimizer استفاده کنید.
اگر بازم با ایپی 6 مشکل داشتید با ایپی 4 تست کنید
اگر tcp no delay خاموش بوده با روشن تست کنید
اینطوری میشه فهمید تقریبا که مشکل از کجاست .

**Comment by hitcher406** [comment]
خیلی ممنون از راهنماییتون

فکر کنم مشکل از اینجاست که من داخل پنل های xray پورت ۴۴۳ و ۸۰ UDP رو بلاک میکنم

با توجه به اینکه از TCP استفاده میکنم به نظرتون ممکنه از این باشه؟
و اینکه تمامی مواردی که گفتین رو انجام دادم مول اوپتیمایزر سرور
Tcp no delay روشن هست
روی هر سرور صد اکانت هست که معمولا سی چهل نفر آنلاینی داریم همزمان
6to4 نیست
ریست تایمر دو ساعت هست

نمیدونم چطور میشه فهمید روی آیپی ۶ اختلال هست یا نه
از سرورهای خارج پینگ میدن منظم ولی اینکه تو یه بحظاتی اختلال بیاد رو نمیدونم

**Comment by Azumi67** [comment]
بله میتونه از پورت هم باشه . اما شما گفتید ریست تایم دو ساعته هست اما اونجا نشون داده که 3 ساعت کار میکرده. باید بررسی کنید که همه سرور ها دو ساعته باشند. باید به طور مداوم، لاگ های تانلتون رو نگاه کنید و ببینید چه لاگ هایی دریافت میکنید. در سرور خارج ایپی 6 دیگری بسازید و با اونم تست کنید.

**Comment by hitcher406** [comment]
این وضعیت الان هست
لاگ سرور ایران
● iran-azumi.service - Iran-Azumi Service
     Loaded: loaded (/etc/systemd/system/iran-azumi.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-01-08 13:06:48 UTC; 6h ago
   Main PID: 26380 (rathole)
      Tasks: 3 (limit: 2178)
     Memory: 43.1M
        CPU: 1h 36min 36.448s
     CGroup: /system.slice/iran-azumi.service
             └─26380 /root/rathole/target/debug/rathole /root/rathole/server.toml

Jan 08 19:46:19 x9kx6a05pl rathole[26380]: 2024-01-08T19:46:19.783253Z ERROR connection{addr=[::ffff:43.132.196.160]:46126}: rathole::server: Failed to deserialize hello: invalid value: integer `1684611707`, expected variant index 0 <= i < 2
Jan 08 19:46:25 x9kx6a05pl rathole[26380]: 2024-01-08T19:46:25.869511Z ERROR connection{addr=[::ffff:43.132.196.160]:48268}: rathole::server: Failed to deserialize hello: invalid value: integer `542393671`, expected variant index 0 <= i < 2
Jan 08 19:46:27 x9kx6a05pl rathole[26380]: 2024-01-08T19:46:27.449844Z ERROR connection{addr=[::ffff:43.132.196.160]:48610}: rathole::server: Failed to read hello: early eof
Jan 08 19:46:29 x9kx6a05pl rathole[26380]: 2024-01-08T19:46:29.875834Z ERROR connection{addr=[::ffff:43.132.196.160]:50982}: rathole::server: Failed to deserialize hello: invalid value: integer `66326`, expected variant index 0 <= i < 2
Jan 08 19:46:30 x9kx6a05pl rathole[26380]: 2024-01-08T19:46:30.834577Z ERROR connection{addr=[::ffff:43.132.196.160]:50182}: rathole::server: Failed to read hello: early eof
Jan 08 19:46:37 x9kx6a05pl rathole[26380]: 2024-01-08T19:46:37.039734Z ERROR connection{addr=[::ffff:43.132.196.160]:53016}: rathole::server: Failed to read hello: early eof
Jan 08 19:46:39 x9kx6a05pl rathole[26380]: 2024-01-08T19:46:39.623874Z ERROR connection{addr=[::ffff:43.132.196.160]:54708}: rathole::server: Failed to read hello: early eof
Jan 08 19:46:43 x9kx6a05pl rathole[26380]: 2024-01-08T19:46:43.821960Z ERROR connection{addr=[::ffff:43.132.196.160]:56078}: rathole::server: Failed to read hello: early eof
Jan 08 19:46:45 x9kx6a05pl rathole[26380]: 2024-01-08T19:46:45.998078Z ERROR connection{addr=[::ffff:43.132.196.160]:57964}: rathole::server: Failed to read hello: early eof
Jan 08 20:01:56 x9kx6a05pl rathole[26380]: 2024-01-08T20:01:56.920545Z ERROR connection{addr=[::ffff:23.92.21.96]:33216}: rathole::server: Failed to deserialize hello: invalid value: integer `66326`, expected variant index 0 <= i < 2
~



ببینین من دو ساعت زدم ریست رو ولی شش ساعت هست فعال هست سرور ایران که شش ساعت پیش دستی ری استارت کردم
.
.
.
.

اینم لاگ سرور خارج هست


 kharej-azumi.service - Kharej-Azumi Service
     Loaded: loaded (/etc/systemd/system/kharej-azumi.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-01-08 16:25:40 UTC; 3h 36min ago
   Main PID: 545041 (rathole)
      Tasks: 5 (limit: 4524)
     Memory: 52.3M
        CPU: 18min 8.448s
     CGroup: /system.slice/kharej-azumi.service
             └─545041 /root/rathole/target/debug/rathole /root/rathole/client.toml

Jan 08 16:25:40 N1 rathole[545041]: 2024-01-08T16:25:40.748492Z  INFO handle{service=kharej6}:run: rathole::client: Control channel established
Jan 08 16:25:40 N1 rathole[545041]: 2024-01-08T16:25:40.751098Z  INFO handle{service=kharej2}:run: rathole::client: Control channel established
Jan 08 16:25:40 N1 rathole[545041]: 2024-01-08T16:25:40.753404Z  INFO handle{service=kharej4}:run: rathole::client: Control channel established
Jan 08 16:25:40 N1 rathole[545041]: 2024-01-08T16:25:40.756383Z  INFO handle{service=kharej5}:run: rathole::client: Control channel established
Jan 08 16:25:40 N1 rathole[545041]: 2024-01-08T16:25:40.870438Z  INFO handle{service=kharej1}:run: rathole::client: Control channel established
Jan 08 17:34:50 N1 rathole[545041]: 2024-01-08T17:34:50.889338Z  WARN handle{service=kharej4}:run: rathole::client: Failed to run the data channel: Failed to connect to 127.0.0.1:41579: Connection refused (os error 111)
Jan 08 17:34:50 N1 rathole[545041]: 2024-01-08T17:34:50.895240Z  WARN handle{service=kharej5}:run: rathole::client: Failed to run the data channel: Failed to connect to 127.0.0.1:23010: Connection refused (os error 111)
Jan 08 17:34:50 N1 rathole[545041]: 2024-01-08T17:34:50.895630Z  WARN handle{service=kharej5}:run: rathole::client: Failed to run the data channel: Failed to connect to 127.0.0.1:23010: Connection refused (os error 111)
Jan 08 17:34:50 N1 rathole[545041]: 2024-01-08T17:34:50.906933Z  WARN handle{service=kharej5}:run: rathole::client: Failed to run the data channel: Failed to connect to 127.0.0.1:23010: Connection refused (os error 111)
Jan 08 17:34:59 N1 rathole[545041]: 2024-01-08T17:34:59.086841Z  WARN handle{service=kharej4}:run: rathole::client: Failed to run the data channel: Failed to connect to 127.0.0.1:41579: Connection refused (os error 111)
~
~
~
الان بدون هیچ مشکلی کانفیگ ها وصل هستن ولی داخل لاگ ارور زده و نتونسته اتصال به پورت 41579 و 23010 رو برقرار کنه اما همین الان این پورت ها وصل هستن.

به نظرتون مشکل از ریست تایمر هست؟ چون من مطمئن هستم برای تمام سرورها دو ساعت رو وارد کردم

**Comment by Azumi67** [comment]
شما این دو تا فایل رو داخل سرور هاتون نگاه کنید . nano /etc/rat.sh
و داخل crontab -e هم نگاه کنید که اضافه شده یا خیر.
سپس این کار هم زمان در سرور خارج و ایران انجام دهید و نتیجه رو ببینید
bash /etc/rat.sh

**Comment by hitcher406** [comment]
سرور ایران 
nano /etc/rat.sh
#!/bin/bash
sudo systemctl daemon-reload
sudo systemctl restart iran-azumi
sudo sync; echo 1 > /proc/sys/vm/drop_caches
sudo journalctl --vacuum-size=1M
----------------------------------
crontab -e
0 */2 * * * /etc/rat.sh

-------------------------------------

سرور خارج
nano /etc/rat.sh

#!/bin/bash
sudo systemctl daemon-reload
sudo systemctl restart kharej-azumi
sudo sync; echo 1 > /proc/sys/vm/drop_caches
sudo journalctl --vacuum-size=1M

-------------------------------------------------
crontab -e
0 */2 * * * /etc/rat.sh


----------------------
bash /etc/rat.sh 
رو همزمان زدم سرویس ها ری استارت شد
خیلی ممنونم از راهنمایی هاتون
مشکل رو متوجه نشدم از کجا بود ولی، به نظرتون دیگه خودکار ری استارت سرویسها انجام خواد شد؟

**Comment by Azumi67** [comment]
سرویس ها به نظر درست هستن اما یک چیزی باعث میشه که بر روی سرور شما اجرا نشوند چون 6 ساعت بدون ریست بوده
میشه به جای کرون جاب حتی از systemd برای ریستارت دو ساعته استفاده کرد. کمی در موردش مطالعه کنید.
chmod +x etc/rat.sh

**Comment by hitcher406** [comment]
بسیار ممنونم ازتون
تا فردا لاگها رو چک میکنم و درصورت لزوم از systemd هم انجام میدم و نتیجه رو مینویسم اینجا
بازم تشکر از وقتی که گذاشتین
واقعا لطف کردین

**Comment by hitcher406** [comment]
خیلی داخل کرون امتحان کردم همون دستور شمارو 
0 */2 * * * /etc/rat.sh
دسترسی هاشو با chmod +x /etc/rat.sh زدم ولی بازم ریست نمیکرد سرویس رو


دستور کرون رو گذاشتم روی هر یک ساعت بازم ریست نکرد 
برای امتحان گذاشتم هر پنج دقیقه که اوکی شد!
الان روی هر 59 دقیقه گذاشتم داخل کرون تب و سر هر 59 دقیقه هر دو سرور خارج و ایران ریست میشن و اوکی شد مشکلم!

فقط اینکه داخل لاگ سیستم نگاه میکردم دوبار کرون اجرا میشه، به فاصله یک دقیقه، یکی سر 59دقیقه یکی سر 00 دقیقه. نرمال هست این؟





Jan  9 08:59:01 8cuqb0tyw7 CRON[336672]: (root) CMD (/etc/rat.sh)
Jan  9 08:59:01 8cuqb0tyw7 systemd[1]: Reloading.


CONECTIONS TO IPV6

Jan  9 08:59:09 8cuqb0tyw7 systemd[1]: Starting Refresh fwupd metadata and update motd...
Jan  9 08:59:09 8cuqb0tyw7 systemd[1]: Stopping Iran-Azumi Service...
Jan  9 08:59:09 8cuqb0tyw7 systemd[1]: iran-azumi.service: Deactivated successfully.
Jan  9 08:59:09 8cuqb0tyw7 systemd[1]: Stopped Iran-Azumi Service.
Jan  9 08:59:09 8cuqb0tyw7 systemd[1]: iran-azumi.service: Consumed 6min 14.587s CPU time.
Jan  9 08:59:09 8cuqb0tyw7 systemd[1]: Started Iran-Azumi Service.
Jan  9 08:59:09 8cuqb0tyw7 rathole[336714]: 2024-01-09T08:59:09.520553Z  INFO config_watcher{path="/root/rathole/server.toml"}: rathole::config_watcher: Start watching the config
Jan  9 08:59:09 8cuqb0tyw7 rathole[336714]: 2024-01-09T08:59:09.526537Z  INFO rathole::server: Listening at [::]:443
Jan  9 08:59:09 8cuqb0tyw7 kernel: [228561.007036] rat.sh (336673): drop_caches: 1

CONECTIONS TO IPV6


Jan  9 08:59:11 8cuqb0tyw7 dbus-daemon[750]: [system] Activating via systemd: service name='org.freedesktop.fwupd' unit='fwupd.service' requested by ':1.93' (uid=113 pid=336711 comm="/usr/bin/fwupdmgr refresh " label="unconfined")
Jan  9 08:59:11 8cuqb0tyw7 CRON[336671]: (CRON) info (No MTA installed, discarding output)
Jan  9 08:59:11 8cuqb0tyw7 systemd[1]: Starting Firmware update daemon...
Jan  9 08:59:18 8cuqb0tyw7 dbus-daemon[750]: [system] Successfully activated service 'org.freedesktop.fwupd'
Jan  9 08:59:18 8cuqb0tyw7 systemd[1]: Started Firmware update daemon.
Jan  9 08:59:18 8cuqb0tyw7 systemd[1]: fwupd-refresh.service: Deactivated successfully.
Jan  9 08:59:18 8cuqb0tyw7 systemd[1]: Finished Refresh fwupd metadata and update motd.
Jan  9 09:00:01 8cuqb0tyw7 CRON[336946]: (root) CMD (/etc/rat.sh)
Jan  9 09:00:01 8cuqb0tyw7 systemd[1]: Reloading.



CONECTIONS TO IPV6



Jan  9 09:00:02 8cuqb0tyw7 kernel: [228613.471515] systemd-fstab-generator[336963]: Failed to create unit file /run/systemd/generator/swap.swap, as it already exists. Duplicate entry in /etc/fstab?
Jan  9 09:00:02 8cuqb0tyw7 systemd[336952]: /usr/lib/systemd/system-generators/systemd-fstab-generator failed with exit status 1.
Jan  9 09:00:07 8cuqb0tyw7 systemd[1]: Stopping Iran-Azumi Service...
Jan  9 09:00:07 8cuqb0tyw7 systemd[1]: iran-azumi.service: Deactivated successfully.
Jan  9 09:00:07 8cuqb0tyw7 systemd[1]: Stopped Iran-Azumi Service.
Jan  9 09:00:07 8cuqb0tyw7 systemd[1]: iran-azumi.service: Consumed 18.454s CPU time.
Jan  9 09:00:07 8cuqb0tyw7 systemd[1]: Started Iran-Azumi Service.
Jan  9 09:00:08 8cuqb0tyw7 kernel: [228619.239864] rat.sh (336947): drop_caches: 1

**Comment by Azumi67** [comment]
باید بررسی کنید که چرا اینطوریه . 
grep cron /var/log/syslog
کامند 
*/59 * * * * /etc/rat.sh
