### ISSUE TITLE
اضافه کردن سرور دوم خارج

### ISSUE THREAD

**Issue by sarboy1371** [Azumi67/Rathole_reverseTunnel#10]
امکانش هست سرور دوم و سوم و ... به مرور زمان اضافه بشه؟ یا همه شون باید موقع تانل زدن اضافه بشه(همون اول کار )؟؟؟

**Comment by Azumi67** [comment]
سلام. این که به مرور زمان اضافه بشه موضوعی هست که باید در قسمت edit بهش اضافه کنم .
