### ISSUE TITLE
اجرای اسکریپت

### ISSUE THREAD

**Issue by javad48** [Azumi67/Rathole_reverseTunnel#11]
سلام و وقت بخیر.
مشکل من با این اسکریپت و ریورس اینه که بعد از اینکه از محیط ترمینال خارج میشم نمیتونم اسکریپت رو ران کنم و باید لینک نصب رو بزنم تا اسکریپت بیاد.
میتونید منو راهنمایی کنید چه دستوری باید بزنم؟

**Comment by Azumi67** [comment]
سلام . اسکریپت گو داخل سرور شما در قسمت روت باید باشه . با دستور go run میتونید اسکریپت رو اجرا کنید .
