### ISSUE TITLE
tunnel

### ISSUE THREAD

**Issue by nimaafallah** [Azumi67/Rathole_reverseTunnel#12]
سلام
برای برقرار کردن تانل، باید تعداد پورت ها مشخص بشه و اعدادش داده بشه، بصورت وارد کردن رنج پورت راهی هست برای انجام تانل؟
مثلا من 100 تا یوزر دارم، سخته همه پورتها بصورت دستی وارد بشه. راهی هست که رنج پورت ها رو براش مشخص کرد؟

**Comment by Azumi67** [comment]
سلام . برای اینکه چندین پورت به تعداد زیاد انجام بشه بهتره که خود سازنده تانل، نخست اینکار رو انجام دهد و بعد به صورت اسکریپت وارد شود اگر به طور مثال داخل اسکریپت مقدار زیادی پورت را قرار دهیم نمیدونم چه مقدار منابع مصرف میکند چون تست هم نکردم .

**Comment by nimaafallah** [comment]
اگه راه اضافه کردن رنج پورت رو بگید میتونم تست کنم اطلاع بدم.

**Comment by Azumi67** [comment]
شما باید تک تک پورت ها رو اضافه کنید . این کار با اسکریپت راحت تر هست . مثلا شما میگید بین 5080 تا 6080 می‌خوام و اسکریپت این کانفیگ رو اضافه کنه . میتونید از اسکریپت اون گیت هاب دیگری که داخل صفحه قرار دادم استفاده کنید. بعد برید از ai بپرسید و به صورت bash اینکار رو ازش بخواهید . براتون احتمالا بتونه درست کنه و به اسکریپت ایشون اضافه کنید و استفاده کنید . البته پروژه ایشون رو فورک کنید که ناراحتی هم برای ایشون پیش نیاد.ببینید میشه یا نه که بعد من روی گو اضافه کنم چون فعلا‌ وقت تست کردن این مورد رو ندارم .

**Comment by elyarsa** [comment]
با سلام
پورت ۶۵۰۰۰-۵۴ رو داخل فایل کانفیگ فوروارد کردم
برای سرور ۲ هسته درصد مصرف منابع به ۹۰ درصد رسید

**Comment by Azumi67** [comment]
پس سروری با منابع خوبی میخواد .
