### ISSUE TITLE
مشکل در تک سرور

### ISSUE THREAD

**Issue by mehranweb** [Azumi67/Rathole_reverseTunnel#13]
سلام
وقت بخیر
ابتدا تشکر می کنم بابت زحماتتون که بی دریغ منتشر می کنید.
در نسخه قبل که برای تک سرور بود، کاملا بدون ایراد کار می کرد، اما در نسخه جدید، در منوی اول، برای تک سرور فیلد مشخصی تعبیه نشده و با هرکدام از گزینه های دو و سه که راه اندازی می کنم، زمانی که استاتوس رو بررسی می کنم می بینم که هیچ کانفیگی درست نشده، اما در نسخه قبل بدون هیچ مشکلی کار میکرد. من بر روی اوبونتوی 24 و دبیان 11 که تازه نصب شده بودن تست کردم.

**Comment by Azumi67** [comment]
سلام مرسی. گزینه ها اونجا زیادن . لطفاً بگید کدوم گزینه رو انتخاب کردید . بعد اینکه استاتوس هر روش داخل خود اون منو قرار داده شده . مثلا روش ده سرور‌ خارج یک سرور ایران ، برای خودش استاتوس دارد . چیز در تک سرور تغییر داده نشده اما بهم بگید کدوم گزینه که منم بررسی کنم

**Comment by mehranweb** [comment]
عرض کنم خدمت شما که من برای تک سرور، هم با گزینه 2 و هم با گزینه 3 تست کردم، اما زمانی که استاتوس میگیرم ساخته نمیشه، قبلش دبیان 11 داشتم و گفتم شاید با این نسخه هم خوانی نداره اما با اوبونتو 24 هم همین میشکل هست.
به ایمیل تون دسترسی سرور رو بفرستم؟
یه سوال دیگه هم داشتم بین این تانل و تانل چیزل کدام سرعت بهتری داره و چجوری میشه بنچ مارک گرفت؟

**Comment by Azumi67** [comment]
من الان هم ده سرور خارج تک سرور ایران گزینه دومش رو تست کردم و کار کرد و هم پنج سرور ایران و تک سرور خارج گزینه دوم ipv4 تست کردم و کار کرد

**Comment by Azumi67** [comment]
من کامل تست کردم کار می‌کنه . فقط قسمت استاتوس داخل سرور ایران برای پنج سرور ایران و یک سرور خارج، به درستی نشون نمیداد که آپدیت دادم .

**Comment by mehranweb** [comment]
ممنون از زحماتتون،
مثل قبل به حالت کامپایل نصب کردم و اوکی شد. چیزی که متوجه شدم اینه که با نسخه دبیا 11 و اوبونتوی 20 که اکثر دیتاسنترها تا همین نسخه رو دارن حتما باید کامپایلی نصب رو انجام داد اما با نسخه اوبونتوی 24  نصب باینری هم اوکی بود.

ممنون از زحماتتون

**Comment by Azumi67** [comment]
بله برای همین هم بایناری و هم به صورت کامپایل قرار دادم . خواهش میکنم.
