### ISSUE TITLE
نبودن گزینه نصب تک سرور

### ISSUE THREAD

**Issue by Sharevex** [Azumi67/Rathole_reverseTunnel#14]
سلام وقتتون بخیر 
من از نسخه باینری استفاده میکنم ولی گزینه تک سرور واسم نمیاد ، مشکل از سمت اسکریپت هست یا روش نصب تک سرور متفاوت هستش ؟

**Comment by Azumi67** [comment]
سلام. خب برید داخل گزینه دوم ده خارج و یک ایران . داخل سرور خارج سرور یک خارج را انتخاب کنید و داخل سرور ایران ،‌ گزینه ایران را انتخاب میکنید. اینطوری میتوانید به صورت تک سرور استفاده نمایید .
