### ISSUE TITLE
ubuntu 20

### ISSUE THREAD

**Issue by AliHemmati79** [Azumi67/Rathole_reverseTunnel#15]
سلام ممنون بابت اسکریپ خوبتون
ورژن 20 اوبونتو برای این اسکریپ مناسبه یا از 22 استفاده کنم؟

**Comment by Azumi67** [comment]
سلام. Yw
با Ubuntu 20 تنها با کامپایل میتوانید از این تانل استفاده کنید. بهتره آپگرید کنید .

**Comment by parhampahlevann** [comment]
سلام و خسته نباشید خدمت ازومی عزیز موقع نصب پروژه روی سرور ایران خطای  /dev/fd/63: line 37: go: command not found دریافت میکنم از چی میتونه باشه لطفا راهنمایی کنید ممنون

**Comment by AliHemmati79** [comment]
> سلام. Yw با Ubuntu 20 تنها با کامپایل میتوانید از این تانل استفاده کنید. بهتره آپگرید کنید .

سلام مجدد
با اوبونتو۲۰ کامپایل کردم بدون مشکل کار میکنه
چون تو سرور خارج برخی موارد باید رو اوبونتو ۲۰ باشه نمیتونم اپگریدش کنم
سرور ایران ابونتو۲۲ باشه خارج ۲۰ مشکلی پیش میاد یا نه؟

**Comment by Azumi67** [comment]
> > سلام. Yw با Ubuntu 20 تنها با کامپایل میتوانید از این تانل استفاده کنید. بهتره آپگرید کنید .
> 
> سلام مجدد با اوبونتو۲۰ کامپایل کردم بدون مشکل کار میکنه چون تو سرور خارج برخی موارد باید رو اوبونتو ۲۰ باشه نمیتونم اپگریدش کنم سرور ایران ابونتو۲۲ باشه خارج ۲۰ مشکلی پیش میاد یا نه؟

سلام . نه نباید مشکلی باشه .

**Comment by AliHemmati79** [comment]
> > > سلام. Yw با Ubuntu 20 تنها با کامپایل میتوانید از این تانل استفاده کنید. بهتره آپگرید کنید .
> > 
> > 
> > سلام مجدد با اوبونتو۲۰ کامپایل کردم بدون مشکل کار میکنه چون تو سرور خارج برخی موارد باید رو اوبونتو ۲۰ باشه نمیتونم اپگریدش کنم سرور ایران ابونتو۲۲ باشه خارج ۲۰ مشکلی پیش میاد یا نه؟
> 
> سلام . نه نباید مشکلی باشه .

ممنون🌹
