### ISSUE TITLE
عدم دسترسی به تمامی وبسایت ها

### ISSUE THREAD

**Issue by elyarsa** [Azumi67/Rathole_reverseTunnel#16]
با سلام
گاهی اوقات کانفیگ 2ray پینگ نمیده و اینستاگرام رو باز نمیکنه ولی تلگرام و برخی از سایت های فیلتر کار میکنن
با ریست xray یا ریست تانل مشکل رفع و اتصال برقرار میشه
ریست تایم هم 4 ساعته
مشکل از چی میتونه باشه؟

**Comment by Azumi67** [comment]
سلام. باید موقع این مشکل لاگ های x-ray و رت هول رو مشاهده کنید . احتمالش هست که از سمت پنلتون باشه و یک مشکلی اونجا وجود داشته باشه که باید بررسی کنید . اگر نتونستید مشکل رو پیدا کنید فعلا میتونید با ریست خودکار پنلتون این مشکل رو حل کنید یا بر روی سرور جدیدی بروید .

**Comment by elyarsa** [comment]
با تشکر از پاسخگوییتون
متاسفانه 4 تا سرور از سمت کشور های مختلف دارم که همشون این ایراد رو دارن
زمان خاصی هم برای این مورد وجود نداره 
مثلا یکی ازسرور ها الان به این صورته
لاگ xui هم چیزی نشون نمیده

log iran :

Jun 23 06:24:14 ubuntu rathole[2217219]: 2024-06-23T02:54:14.378059Z ERROR connection{addr=138.197.15.182:56308}: rathole::server: Failed to deserialize hello: inva>Jun 23 06:24:14 ubuntu rathole[2217219]: 2024-06-23T02:54:14.714430Z ERROR connection{addr=138.197.15.182:56322}: rathole::server: Failed to deserialize hello: inva>Jun 23 06:24:15 ubuntu rathole[2217219]: 2024-06-23T02:54:15.052019Z ERROR connection{addr=138.197.15.182:56336}: rathole::server: Failed to deserialize hello: inva>Jun 23 06:24:15 ubuntu rathole[2217219]: 2024-06-23T02:54:15.406402Z ERROR connection{addr=138.197.15.182:56352}: rathole::server: Failed to deserialize hello: inva>Jun 23 06:24:15 ubuntu rathole[2217219]: 2024-06-23T02:54:15.738852Z ERROR connection{addr=138.197.15.182:56356}: rathole::server: Failed to deserialize hello: inva>Jun 23 06:24:16 ubuntu rathole[2217219]: 2024-06-23T02:54:16.074592Z ERROR connection{addr=138.197.15.182:56372}: rathole::server: Failed to deserialize hello: inva>Jun 23 06:24:16 ubuntu rathole[2217219]: 2024-06-23T02:54:16.400474Z ERROR connection{addr=138.197.15.182:56382}: rathole::server: Failed to deserialize hello: inva>Jun 23 06:24:16 ubuntu rathole[2217219]: 2024-06-23T02:54:16.740872Z ERROR connection{addr=138.197.15.182:56398}: rathole::server: Failed to deserialize hello: inva>Jun 23 06:25:52 ubuntu rathole[2217219]: 2024-06-23T02:55:52.865803Z ERROR connection{addr=161.35.236.158:54288}: rathole::server: Failed to deserialize hello: inva>Jun 23 06:39:54 ubuntu rathole[2217219]: 2024-06-23T03:09:54.379324Z ERROR connection{addr=188.75.171.194:52349}: rathole::server: Failed to deserialize hello: inva>~








log kharej

Jun 23 04:00:02 9c0beb55-85c9-4b94-8930-062d5ea00f16-76509 rathole[2833694]: 2024-06-23T01:00:02.521004Z  INFO handle{service=kharej6}: rathole::client: Starting 3f>Jun 23 04:00:02 9c0beb55-85c9-4b94-8930-062d5ea00f16-76509 rathole[2833694]: 2024-06-23T01:00:02.521053Z  INFO handle{service=kharej3}: rathole::client: Starting fd>Jun 23 04:00:02 9c0beb55-85c9-4b94-8930-062d5ea00f16-76509 rathole[2833694]: 2024-06-23T01:00:02.521125Z  INFO handle{service=kharej1}: rathole::client: Starting 98>Jun 23 04:00:02 9c0beb55-85c9-4b94-8930-062d5ea00f16-76509 rathole[2833694]: 2024-06-23T01:00:02.776679Z  INFO handle{service=kharej1}:run: rathole::client: Control>Jun 23 04:00:02 9c0beb55-85c9-4b94-8930-062d5ea00f16-76509 rathole[2833694]: 2024-06-23T01:00:02.777254Z  INFO handle{service=kharej5}:run: rathole::client: Control>Jun 23 04:00:02 9c0beb55-85c9-4b94-8930-062d5ea00f16-76509 rathole[2833694]: 2024-06-23T01:00:02.778307Z  INFO handle{service=kharej3}:run: rathole::client: Control>Jun 23 04:00:02 9c0beb55-85c9-4b94-8930-062d5ea00f16-76509 rathole[2833694]: 2024-06-23T01:00:02.778886Z  INFO handle{service=kharej2}:run: rathole::client: Control>Jun 23 04:00:02 9c0beb55-85c9-4b94-8930-062d5ea00f16-76509 rathole[2833694]: 2024-06-23T01:00:02.779765Z  INFO handle{service=kharej7}:run: rathole::client: Control>Jun 23 04:00:02 9c0beb55-85c9-4b94-8930-062d5ea00f16-76509 rathole[2833694]: 2024-06-23T01:00:02.780432Z  INFO handle{service=kharej6}:run: rathole::client: Control>Jun 23 04:00:02 9c0beb55-85c9-4b94-8930-062d5ea00f16-76509 rathole[2833694]: 2024-06-23T01:00:02.806258Z  INFO handle{service=kharej4}:run: rathole::client: Control

**Comment by Azumi67** [comment]
شما با پایین آوردن ریست تایمر ببینید مشکلتون بهتر میشه یا نه .

**Comment by elyarsa** [comment]
میخواستم از طریق فایل لاگ اگه مشکلی پیش اومد کرون جاب فعال بشه
اگه امکانش باشه مسیر فایل لاگ رو بگید 
و مشکلی باشه به صورت error نمایش داده میشه یا حالت دیگه ای هم داره؟

**Comment by Azumi67** [comment]
> میخواستم از طریق فایل لاگ اگه مشکلی پیش اومد کرون جاب فعال بشه اگه امکانش باشه مسیر فایل لاگ رو بگید و مشکلی باشه به صورت error نمایش داده میشه یا حالت دیگه ای هم داره؟

فایل لاگ رو باید از طریق همون فایل های سیستمی ببینید چون من جایی ذخیره نکردم . کسی دیگه هم همین مشکل رو داشت که با ریست تایمر پایین تر فعلا مشکلشون برطرف شده.

**Comment by elyarsa** [comment]
ممنون🙏
