### ISSUE TITLE
Why not use the already built binaries for 'rathole'

### ISSUE THREAD

**Issue by OnceUponATimeInAmerica** [Azumi67/Rathole_reverseTunnel#2]
سلام و با تشکر از زحمات متعددتون.

میخواستم علت اینکه به جای استفاده از باینری های پیش ساخته در این اسکریپت، مسیر پرزحمت تر نصب rust و کامپایل و دردسرهای اون انتخاب شده رو جویا بشم.

تا جایی که دیدم پروژه rathole  خودش باینری های بسیار بهینه سازی شده و متعددی رو برای پلتفرم های مختلف کامپیایل و آماده کرده (من روی ⁧debian⁩ استفاده کردم).

در کل ولی تونل بسیار بهینه، پرسرعت؛ پایدار،  کم باگ، سهل الاستفاده و در مجموع  عالی هست (به خاطر بهینگی زبان راست) و بابت معرفی ش به هموطنان ازتون تشکر میکنم.

**Comment by Azumi67** [comment]
سلام . خواهش میکنم. راستش امکانش هست که برای بعضی سرور ها حتی با نصب کردن پیش نیاز ها، باز هم نتوان اجراش کرد و من این رو ریسک رو دیگر نکردم وگرنه کار خودمم راحت تر میشد. چون به راحتی اسم باگ رو روش میذارن و they will move on . شاید مسیر بهترش این بود که هم کامپایل و هم Binary رو قرار میدادم. مرسی
