### ISSUE TITLE
چطوری میشه حذف کرد

### ISSUE THREAD

**Issue by elegance666** [Azumi67/Rathole_reverseTunnel#20]
چطور میشه حذف کرد، دائم روشن میشه هر کاری میکنم پورت ۴۴۳ میگیره

**Comment by Azumi67** [comment]
خود اسکریپت قابلیت پاک کردن هم دارد ، اگر بعد از پاک کردن باز هم اکتیو هست ، در پاک کردن آن اشتباهی انجام دادید .
