### ISSUE TITLE
"Invalid choice." prompt on  install binary's choice

### ISSUE THREAD

**Issue by A2116** [Azumi67/Rathole_reverseTunnel#21]
Hi
When i select 1 to install binary's it prompt "Invalid choice."
what should i do?

**Comment by Azumi67** [comment]
Hi, on which script command are you having this specific problem?
Because I have two different scripts for binary and non binary.
Gimme that command so i can check it out myself later.

**Comment by Azumi67** [comment]
now it should be fixed.
