### ISSUE TITLE
پنل بر روی ایران

### ISSUE THREAD

**Issue by usamirali** [Azumi67/Rathole_reverseTunnel#22]
سلام وققتون بخیر و ممنون از زحماتتون
من میخوام 3 تا سرور ایران رو به صورت مالتی پورت وصل کنم به یک خارج و پنل ها روی ایران باشه همچین چیزی امکانش هست با این اسکریپ؟؟؟

**Comment by Azumi67** [comment]
سلام. این ریورس تانل نیاز به این دارد که پنل در سرور خارج باشد اما شاید بشود در خود پنل کارهایی انجام داد که این پنل در سرور ایران باشد اما چون خودم تست نکردم نمیتونم پاسخ قاطعی هم به شما بدم .
