### ISSUE TITLE
How to Uninstall?

### ISSUE THREAD

**Issue by MJamshidnejad** [Azumi67/Rathole_reverseTunnel#23]
Hello

I would like to know how can I uninstall the script?

**Comment by Azumi67** [comment]
Hello, there is an uninstall option in the script itself.

**Comment by MJamshidnejad** [comment]
I'm afraid I couldn't find it. Can you help me?

**Comment by Azumi67** [comment]
In the script, use the down arrow key to get to the bottom of the main menu. The uninstall option is there.
