### ISSUE TITLE
مشکل پینگ بالا و افت سرعت

### ISSUE THREAD

**Issue by mehrdadghadam** [Azumi67/Rathole_reverseTunnel#24]
من روزی 3 بار هی سرورم سرعتش داغون میشه پینگ از رو 300 میره رو 5000
بعد تانل رو دوباره دستی از اول میزنم مشکلش حل میشه
مشکل از چی میتونه باشه
ریست تایمر هم با عددای مختلف تست کردم
heartbeat
noise tls
با این ارتباط رو زدم
پنل هم مرزبان هست
ممنون میشم کمکم کنید

**Comment by Azumi67** [comment]
شما بررسی کنید که ریست تایمر به درستی انجام می‌شود . اگر مشکلی در ریست تایمر داشتید باید ریست تایمر بوسیله custom daemon انجام شود که احتمالا خودم این مورد رو به اسکریپت اضافه خواهم کرد .در موردش بخونید .

**Comment by mehrdadghadam** [comment]
از کدوم قسمت چک کنم ؟

**Comment by Azumi67** [comment]
استاتوس سرویس ها را بررسی کنید. اگر ریست انجام شود، تایمر استاتوس هم ریست میشود یا به صورت tail یا journalctl هم میتوانید بررسی کنید. ریست تایمر 5 دقیقه ، قطعی ها حس میشود. در مورد custom daemon مطالعه کنید.

**Comment by mehrdadghadam** [comment]
فکر میکنم ریست انجام نمیشود
اگه میشه یک راه سریع و اسون جهت تتنظیم ریست بهم بگید
کاربر مبتدی هستم
اگه مرحله به مرحله و یا اموزش ارسال کنید ممنون میشم

**Comment by Azumi67** [comment]
ممکنه باید بررسی بشه . من بعدا یک ریست تایمر به جای کرون اضافه میکنم . اگر عجله ای ندارید میتونید برای اون آپدیت هم صبر کنید .
با htop دلیل مصرف بالای CPU را پیدا کنید .
تمام این مطالب را میتوانید از ai chatgpt سوال کنید .

**Comment by mehrdadghadam** [comment]
مربوط به تانل هست
میزان مصرف ضمیمه شد
![Uploading Screenshot 2024-09-09 162306.png…]()

**Comment by mehrdadghadam** [comment]
![Uploading Screenshot 2024-09-09 162306.png…]()

**Comment by mehrdadghadam** [comment]
مشکل من مربوط به مصرف سی پی یو بود
برای 200 یوزر داره 4 هسته هم رو ایران هم رو خارج پر میکنه
مشکل از چی هست؟

**Comment by Azumi67** [comment]
اگر با ریست manual درست شده پس باید با ریست daemon هم درست بشه که در اون صورت باید صبر کنید که به اسکریپت اضافه بشود .

**Comment by mehrdadghadam** [comment]
الان نمیشه کاری کرد مصرف منابع عادی شه؟
کی اضافه میشه؟
با تشکر

**Comment by Azumi67** [comment]
شما با Binary اجرا کردید ؟ چون برای اون دارم الان اپدیت میدم

**Comment by mehrdadghadam** [comment]
sudo apt install curl -y && bash <(curl -s https://raw.githubusercontent.com/Azumi67/Rathole_reverseTunnel/main/install.sh)

آین و heartbeat
compile هست ظاهرا

**Comment by Azumi67** [comment]
شما 5 دقیقه دیگر اپدیت جدید را تست کنید و ریست تایمر مورد نظر خودتون را فعال کنید. زیاد وقت نکردم تست کنم
