### ISSUE TITLE
crontab

### ISSUE THREAD

**Issue by AliHemmati79** [Azumi67/Rathole_reverseTunnel#25]
سلام وقت بخیر
روی اوبونتو 22 از طریق باینری نصب کردم و ریست تایم سرور ایران و خارج گذاشتم روی 5 دقیقه ولی داخل کرون جاب هیچی نیست و خالیه
اما ارتباط تانلینگ برقراره
به نظرتون مشکل خاصی وجود داره که نشون نمیده یا جدیدا اینجوری شده بعد اپدیت؟
اگر نیازی هست جاهای دیگری هم بررسی بشه ممنون میشم کد دستوریشون برام بفرستین

**Comment by Azumi67** [comment]
> سلام مجدد این مورد رفع شد، ریست تایمرش گذاشتم روی 1 ساعت ولی به ساعت ما هر هر ساعت دقیق خودش ریست نمیشه مثلا باید تو ساعت های 10.11.12 ریستارت بشه ولی 10:30.11:30.12:30 ریستارت میشه میخوام هر ساعت همون اولش ریستارت بشه چه کاری باید انجام بدم؟
> 
> ***و یک نقطه مهم که روی 4تا سرور ایران تست کردم ، rat_reset.service بعد از اتمام نصب و راه اندازی از قسمت سرویس ها فیلد میده و اجرا نمیشه برای ریستارت محتوای اسکریپت rat_daemon.sh باید ادیت بشه و آخر حلقه done باشه بعد از انجام اینکار سرویس به حالت رانینگ عوض میشه و کار میکنه
> 
> مشاهده وضعیت همه سرویس‌ها: systemctl list-units --type=service
> 
> بررسی محتوای اسکریپت rat_daemon.sh: cat /usr/local/bin/rat_daemon.sh
> 
> برای ویرایش و افزودن done در حلقه اخر اسکریپت استفاده از nano:
> 
> sudo nano /usr/local/bin/rat_daemon.sh
> 
> 5- به انتهای فایل بروید و اطمینان حاصل کنید که done در انتهای حلقه while وجود دارد. باید چیزی شبیه به این باشد:
> 
> #!/bin/bash INTERVAL=300
> 
> while true; do /bin/bash /etc/rat.sh sleep $INTERVAL done
> 
> تغییرات را ذخیره کنید و از ویرایشگر خارج شوید:
> 
> ```
> برای ذخیره فایل، کلید Ctrl + O را فشار دهید، سپس Enter را بزنید.
> برای خروج از ویرایشگر، کلید Ctrl + X را فشار دهید.
> ```
> 
> ***بعد از اصلاح اسکریپت، اطمینان حاصل کنید که فایل اجرایی است:
> 
> sudo chmod +x /usr/local/bin/rat_daemon.sh
> 
> سپس سرویس را دوباره راه‌اندازی کنید:
> 
> sudo systemctl restart rat_reset.service

بله باید آخر فایل daemon یک done اضافه بشه که خودتون اضافه کردید.بعدا به اسکریپت اضافه میکنم .

**Comment by AliHemmati79** [comment]
> > سلام مجدد این مورد رفع شد، ریست تایمرش گذاشتم روی 1 ساعت ولی به ساعت ما هر هر ساعت دقیق خودش ریست نمیشه مثلا باید تو ساعت های 10.11.12 ریستارت بشه ولی 10:30.11:30.12:30 ریستارت میشه میخوام هر ساعت همون اولش ریستارت بشه چه کاری باید انجام بدم؟
> > ***و یک نقطه مهم که روی 4تا سرور ایران تست کردم ، rat_reset.service بعد از اتمام نصب و راه اندازی از قسمت سرویس ها فیلد میده و اجرا نمیشه برای ریستارت محتوای اسکریپت rat_daemon.sh باید ادیت بشه و آخر حلقه done باشه بعد از انجام اینکار سرویس به حالت رانینگ عوض میشه و کار میکنه
> > مشاهده وضعیت همه سرویس‌ها: systemctl list-units --type=service
> > بررسی محتوای اسکریپت rat_daemon.sh: cat /usr/local/bin/rat_daemon.sh
> > برای ویرایش و افزودن done در حلقه اخر اسکریپت استفاده از nano:
> > sudo nano /usr/local/bin/rat_daemon.sh
> > 5- به انتهای فایل بروید و اطمینان حاصل کنید که done در انتهای حلقه while وجود دارد. باید چیزی شبیه به این باشد:
> > #!/bin/bash INTERVAL=300
> > while true; do /bin/bash /etc/rat.sh sleep $INTERVAL done
> > تغییرات را ذخیره کنید و از ویرایشگر خارج شوید:
> > ```
> > برای ذخیره فایل، کلید Ctrl + O را فشار دهید، سپس Enter را بزنید.
> > برای خروج از ویرایشگر، کلید Ctrl + X را فشار دهید.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ***بعد از اصلاح اسکریپت، اطمینان حاصل کنید که فایل اجرایی است:
> > sudo chmod +x /usr/local/bin/rat_daemon.sh
> > سپس سرویس را دوباره راه‌اندازی کنید:
> > sudo systemctl restart rat_reset.service
> 
> بله باید آخر فایل daemon یک done اضافه بشه که خودتون اضافه کردید.بعدا به اسکریپت اضافه میکنم .

این ساعت ریست شدن رو چطور باید تنظیم کنم تا در اوایل هرساعت انجام بشه؟

**Comment by Azumi67** [comment]
ریست این سرویس بر اساس Interval که بر پایه seconds است، میباشد. برای اینکه هر یک ساعت ریست شود بعد از ست کردن تایم، یک بار سرویس ها را در سرور ایران و خارج هم زمان ریست کنید تا ریست تایمر سرویس هر سرور با هم دیگر sync شود

**Comment by AliHemmati79** [comment]
> ریست این سرویس بر اساس Interval که بر پایه seconds است، میباشد. برای اینکه هر یک ساعت ریست شود بعد از ست کردن تایم، یک بار سرویس ها را در سرور ایران و خارج هم زمان ریست کنید تا ریست تایمر سرویس هر سرور با هم دیگر sync شود

بله تا اینجا درسته
الان چک کردم منطقه زمانی سرور utc هست 

برای تبدیل ساعت از UTC به ساعت تهران، که در حال حاضر دارای اختلاف زمانی 3:30+ است، کافی است 3 ساعت و 30 دقیقه به ساعت UTC اضافه کنید.

    ساعت 14:00:00 UTC + 3:30 = 17:30:00 تهران

بنابراین، ساعت 14:00:00 UTC برابر با 17:30:00 در تهران است.


*به نظرم برای اینه که هر ساعت نیمش ریستارت میشه برای وقت محلی ما
برای تغییر این وضعیت باید منطقه زمانی سرور عوض کنم تا این مورد برطرف بشه؟

**Comment by Azumi67** [comment]
> > ریست این سرویس بر اساس Interval که بر پایه seconds است، میباشد. برای اینکه هر یک ساعت ریست شود بعد از ست کردن تایم، یک بار سرویس ها را در سرور ایران و خارج هم زمان ریست کنید تا ریست تایمر سرویس هر سرور با هم دیگر sync شود
> 
> بله تا اینجا درسته الان چک کردم منطقه زمانی سرور utc هست
> 
> برای تبدیل ساعت از UTC به ساعت تهران، که در حال حاضر دارای اختلاف زمانی 3:30+ است، کافی است 3 ساعت و 30 دقیقه به ساعت UTC اضافه کنید.
> 
> ```
> ساعت 14:00:00 UTC + 3:30 = 17:30:00 تهران
> ```
> 
> بنابراین، ساعت 14:00:00 UTC برابر با 17:30:00 در تهران است.
> 
> *به نظرم برای اینه که هر ساعت نیمش ریستارت میشه برای وقت محلی ما برای تغییر این وضعیت باید منطقه زمانی سرور عوض کنم تا این مورد برطرف بشه؟

ببینید زمانی که سرویس ریست فعال شود بر اساس اون تایمری‌که دادید دستورات پشت دستور sleep قرار میگیرند و بعد از اجرا دوباره بر اساس اون تایمر ثانیه در پشت دستور sleep قرار میگیرند. شما باید تایمر سرور ایران و خارج را با هم sync کنید که دستورات در زمان مشخصی انجام بشوند و دوباره sleep شوند . با ساعت سیستم شما کاری ندارد .
