### ISSUE TITLE
وصل نشدن روی برخی سرورها

### ISSUE THREAD

**Issue by Amirmmh** [Azumi67/Rathole_reverseTunnel#3]
سلام خسته نباشید
میخواستم بدونم اینکه روش reverse tls شما روی یه سری از سرورها وصل نمیشه مشکل از چی میتونه باشه؟
داخل اون مسیری که گفتین ارورهارو نشون میده چک کردم و هیچ اروری نه روی سرور این و نه روی سرور خارج وجود نداشت و قسمت check status برای هردو سرور،تانل درحال running بود اما وصل نشد

**Comment by Azumi67** [comment]
سلام. روی ایپی 4 تست کردید ؟ تلاش کردید مدل های دیگری هم تست کنید ؟ journalctl -u رو هم نگاه کردید ؟ میتونید تمام اون لاگ ها رو برای من بفرستید ؟ و اینکه هم چنین journalctl هم بفرستید. حتما روش های دیگه از این تانل هم تست کنید .

**Comment by Amirmmh** [comment]
بله روی ایپی ۴ تست کردم و وصل نشد،علی رغم اینکه دوتا سرور دیگه رو دقیقا با همین روش تونستم وصل کنم
سرور خارج رو هم عوض کردم ولی بازم تغییر ایجاد نشد متاسفانه
Jan 13 22:36:37 Alihaghighat5-alaei RTT[107959]:   port: 49914
Jan 13 22:36:37 Alihaghighat5-alaei RTT[107959]: )
Jan 13 22:36:37 Alihaghighat5-alaei RTT[107959]: con.port=443
Jan 13 22:36:37 Alihaghighat5-alaei RTT[107959]: connected to sheypoor.com:443
Jan 13 22:36:37 Alihaghighat5-alaei RTT[107959]: [Error] user connection but no>Jan 13 22:36:37 Alihaghighat5-alaei RTT[107959]: Connected client:
Jan 13 22:36:37 Alihaghighat5-alaei RTT[107959]: address=TransportAddress(
Jan 13 22:36:37 Alihaghighat5-alaei RTT[107959]:   family: "IPv6",
Jan 13 22:36:37 Alihaghighat5-alaei RTT[107959]:   address_v6: [0, 0, 0, 0, 0, >Jan 13 22:36:37 Alihaghighat5-alaei RTT[107959]:   port: 49918
Jan 13 22:36:37 Alihaghighat5-alaei RTT[107959]: )
Jan 13 22:36:37 Alihaghighat5-alaei RTT[107959]: con.port=443
Jan 13 22:36:37 Alihaghighat5-alaei RTT[107959]: connected to sheypoor.com:443
Jan 13 22:36:37 Alihaghighat5-alaei RTT[107959]: [Error] user connection but no>Jan 13 22:36:38 Alihaghighat5-alaei sshd[108317]: Failed password for root from>Jan 13 22:36:38 Alihaghighat5-alaei RTT[107959]: Connected client:
Jan 13 22:36:38 Alihaghighat5-alaei RTT[107959]: address=TransportAddress(
Jan 13 22:36:38 Alihaghighat5-alaei RTT[107959]:   family: "IPv6",
Jan 13 22:36:38 Alihaghighat5-alaei RTT[107959]:   address_v6: [0, 0, 0, 0, 0, >Jan 13 22:36:38 Alihaghighat5-alaei RTT[107959]:   port: 49924
Jan 13 22:36:38 Alihaghighat5-alaei RTT[107959]: )
Jan 13 22:36:38 Alihaghighat5-alaei RTT[107959]: con.port=443
Jan 13 22:36:38 Alihaghighat5-alaei RTT[107959]: Connected client:
Jan 13 22:36:38 Alihaghighat5-alaei RTT[107959]: address=TransportAddress(
Jan 13 22:36:38 Alihaghighat5-alaei RTT[107959]:   family: "IPv6",
Jan 13 22:36:38 Alihaghighat5-alaei RTT[107959]:   address_v6: [0, 0, 0, 0, 0, >Jan 13 22:36:38 Alihaghighat5-alaei RTT[107959]:   port: 49930
Jan 13 22:36:38 Alihaghighat5-alaei RTT[107959]: )
Jan 13 22:36:38 Alihaghighat5-alaei RTT[107959]: con.port=443
Jan 13 22:36:38 Alihaghighat5-alaei RTT[107959]: connected to sheypoor.com:443
Jan 13 22:36:38 Alihaghighat5-alaei RTT[107959]: [Error] user connection but no>Jan 13 22:36:38 Alihaghighat5-alaei RTT[107959]: Connected client:
Jan 13 22:36:38 Alihaghighat5-alaei RTT[107959]: address=TransportAddress(
Jan 13 22:36:38 Alihaghighat5-alaei RTT[107959]:   family: "IPv6",

خب بالایی ها لاگ های journalctl هستن روی سرور ایران

● iran-azumi.service - Iran-Azumi Service
     Loaded: loaded (/etc/systemd/system/iran-azumi.service; enabled; vendor pr>     Active: active (running) since Sat 2024-01-13 21:16:59 CET; 1h 42min ago
   Main PID: 107609 (rathole)
      Tasks: 4 (limit: 2282)
     Memory: 2.3M
     CGroup: /system.slice/iran-azumi.service
             └─107609 /root/rathole/target/debug/rathole /root/rathole/server.t>
Notice: journal has been rotated since unit was started, output may be incomple>lines 1-10/10 (END)

اینا هم لاگ های systemctl روی سرور ایران بودن







Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: Linux version 5.15.0-91-ge>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: Command line: BOOT_IMAGE=/>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: KERNEL supported cpus:
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel:   Intel GenuineIntel
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel:   AMD AuthenticAMD
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel:   Hygon HygonGenuine
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel:   Centaur CentaurHauls
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel:   zhaoxin   Shanghai
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-provided physical RAM>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: NX (Execute Disable) prote>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: SMBIOS 2.8 present.
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: DMI: Hetzner vServer/Stand>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: Hypervisor detected: KVM
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: kvm-clock: Using msrs 4b56>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: kvm-clock: cpu 0, msr 7800>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: kvm-clock: using sched off>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: clocksource: kvm-clock: ma>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: tsc: Detected 2495.310 MHz>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: e820: update [mem 0x000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: e820: remove [mem 0x000a00>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: last_pfn = 0x7cfdc max_arc>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: x86/PAT: Configuration [0->Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: found SMP MP-table at [mem>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: Using GB pages for direct >Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: RAMDISK: [mem 0x335b3000-0>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: ACPI: Early table checksum>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: ACPI: RSDP 0x00000000000F5>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: ACPI: RSDT 0x000000007CFE2>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: ACPI: FACP 0x000000007CFE2>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: ACPI: DSDT 0x000000007CFE0>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: ACPI: FACS 0x000000007CFE0>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: ACPI: APIC 0x000000007CFE2>lines 1-41...skipping...
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: Linux version 5.15.0-91-ge>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: Command line: BOOT_IMAGE=/>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: KERNEL supported cpus:
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel:   Intel GenuineIntel
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel:   AMD AuthenticAMD
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel:   Hygon HygonGenuine
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel:   Centaur CentaurHauls
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel:   zhaoxin   Shanghai
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-provided physical RAM>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: NX (Execute Disable) prote>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: SMBIOS 2.8 present.
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: DMI: Hetzner vServer/Stand>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: Hypervisor detected: KVM
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: Linux version 5.15.0-91-ge>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: Command line: BOOT_IMAGE=/>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: KERNEL supported cpus:
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel:   Intel GenuineIntel
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel:   AMD AuthenticAMD
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel:   Hygon HygonGenuine
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel:   Centaur CentaurHauls
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel:   zhaoxin   Shanghai
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-provided physical RAM>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: BIOS-e820: [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: NX (Execute Disable) prote>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: SMBIOS 2.8 present.
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: DMI: Hetzner vServer/Stand>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: Hypervisor detected: KVM
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: kvm-clock: Using msrs 4b56>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: kvm-clock: cpu 0, msr 7800>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: kvm-clock: using sched off>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: clocksource: kvm-clock: ma>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: tsc: Detected 2495.310 MHz>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: e820: update [mem 0x000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: ACPI: Reserving WAET table>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: No NUMA configuration foundJan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: Faking a node at [mem 0x00>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: NODE_DATA(0) allocated [me>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: Zone ranges:
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel:   DMA      [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel:   DMA32    [mem 0x00000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel:   Normal   empty
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel:   Device   empty
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: Movable zone start for eac>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: Early memory node ranges
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel:   node   0: [mem 0x0000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel:   node   0: [mem 0x0000000>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: Initmem setup node 0 [mem >Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: On node 0, zone DMA: 1 pag>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: On node 0, zone DMA: 97 pa>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: On node 0, zone DMA32: 123>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: ACPI: PM-Timer IO Port: 0x>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: ACPI: LAPIC_NMI (acpi_id[0>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: IOAPIC[0]: apic_id 0, vers>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: ACPI: INT_SRC_OVR (bus 0 b>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: ACPI: INT_SRC_OVR (bus 0 b>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: ACPI: INT_SRC_OVR (bus 0 b>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: ACPI: INT_SRC_OVR (bus 0 b>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: ACPI: INT_SRC_OVR (bus 0 b>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: ACPI: Using ACPI (MADT) fo>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: ACPI: HPET id: 0x8086a201 >Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: smpboot: Allowing 2 CPUs, >Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: PM: hibernation: Registere>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: PM: hibernation: Registere>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: PM: hibernation: Registere>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: PM: hibernation: Registere>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: [mem 0xc0000000-0xfed1bfff>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: Booting paravirtualized ke>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: clocksource: refined-jiffi>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: setup_percpu: NR_CPUS:8192>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: percpu: Embedded 61 pages/>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: pcpu-alloc: s212992 r8192 >Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: pcpu-alloc: [0] 0 1
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: kvm-guest: PV spinlocks di>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: Built 1 zonelists, mobilit>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: Policy zone: DMA32
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: Kernel command line: BOOT_>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: Unknown kernel command lin>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: Dentry cache hash table en>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: Inode-cache hash table ent>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: mem auto-init: stack:off, >Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: Memory: 1914596K/2047464K >Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: SLUB: HWalign=64, Order=0->Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: ftrace: allocating 50637 e>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: ftrace: allocated 198 page>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: rcu: Hierarchical RCU impl>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: rcu:         RCU restricti>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel:         Rude variant of Ta>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel:         Tracing variant of>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: rcu: RCU calculated value >Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: rcu: Adjusting geometry fo>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: NR_IRQS: 524544, nr_irqs: >Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: random: crng init done
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: Console: colour VGA+ 80x25
Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: printk: console [tty1] ena>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: printk: console [ttyS0] en>Jan 13 16:35:51 Ubuntu-2204-jammy-64-minimal kernel: ACPI: Core revision 202107>lines 51-113

اینا لاگ های journalctl روی سرور خارج


● kharej-azumi.service - Kharej-Azumi Service
     Loaded: loaded (/etc/systemd/system/kharej-azumi.service; enabled; vendor >     Active: active (running) since Sat 2024-01-13 19:35:15 UTC; 9ms ago
   Main PID: 24606 (rathole)
      Tasks: 1 (limit: 2244)
     Memory: 1.4M
        CPU: 1ms
     CGroup: /system.slice/kharej-azumi.service
             └─24606 /root/rathole/target/debug/rathole /root/rathole/client.to>
Jan 13 19:35:15 Alihaghighat5-alaei systemd[1]: Started Kharej-Azumi Service.
lines 1-11/11 (END)

اینا هم لاگ های systemctl

**Comment by Azumi67** [comment]
لاگ های journalctl که یکیشون در مورد RTT بود و خارج هم ربطی به rathole نداشت. دقت کنید روی سرور ایران RTT با rathole اختلال ننداخته باشه 
برای journalctl هم باید نام سرویس مربوطه رو بدید . به طور مثال
journalctl -u kharej-azumi.service
اول برید ببینید سرویس دیگه ای مثل RTT روی سرویس ایران وصل نباشه یا اگر نیازی دارید پورت ها با هم اختلال نداشته باشه.
برای status هم لاگ هاش مهمه. حالا بررسی کنید و اطلاع بدید

**Comment by Amirmmh** [comment]
اون رو بررسی میکنم میفرستم حتما
اما یه سوال دیگه که هست اینه ک اگر یه پورت ۴۴۳ برای ساخت کانفیگ داخل پنل داشته باشم،پورت تانل رو بزنم ۴۴۳،آیا میشه پورت یکی از کانفیگارو هم ۴۴۳ بزنم؟
اگر نمیشه راهکار چیه ک بتونم از پورت ۴۴۳ برای کانفیگ هام استفاده کنم

**Comment by Azumi67** [comment]
پورت تانل را غیر از 443 بذارید

**Comment by Amirmmh** [comment]
بله کار کرد،خیلی ممنون
اون دوتا سروری که تانل reverse tunnel ipv4 روشون کار نکرد،سرور ایران رو ریبیلد کردم و دوباره تانل رو انجام دادم و کار کرد
اینطوری که متوجه شدم،عمده مشکلی که میتونه ایجاد شده باشه به خاطر کامپایلر هست معمولا و اون اگر درست نصب بشه معمولا مشکلی ایجاد نخواهد شد
بازم به هرصورت اگر مشکلی بود اعلام میکنم حتما
مرسی از اسکریپت جالب و کاربردیتون ♥️

**Comment by Amirmmh** [comment]
ببخشید میخواستم بدونم روی دوتا سرور خارج وقتی میزنم،حتما پورت کانفیگ ها باید فرق داشته باشه؟

چون روی پورت های مشابه زدم و کار نکرد متاسفانه و ارور eof داد کانفیگ

**Comment by Azumi67** [comment]
پورت ها باید فرق کنند.
