### ISSUE TITLE
بالارفتن پینگ و آن‌استیبل شدن.

### ISSUE THREAD

**Issue by DontJer** [Azumi67/Rathole_reverseTunnel#4]
درود وقت بخیر.
یکی از مشکلاتی که طی سه روز استفاده باهاش روبرو شدم مشکل بالارفتن پینگ سرویس بعضاً به مدت ۱ تا ۲ ساعت بعد استارت سرویس یا حتی یک تا دو روز هست.
طبق بررسی‌هایی که انجام دادم بنظر میرسه مشکل از ریستارت نشدن سرویس باشه. Issue که closed شده بود رو نگاه کردم کرون رو روی نیم ساعت هم قرار دادم اما مشکل حل نشد انگار کرون عمل نمیکنه با ipv6 و ipv4 هم امتحان کردم تفاوتی نداشت بازم پیش میومد با heartbeat و بدون heartbeat هم همینطور از دیتاسنتر های متفاوت ایرانی و خارجی هم استفاده کردم مجددا مشکل پابرجا بود یوزرهای انلاین روی هر سرور به ۱۰۰ نمیرسن. لاگ سرور هم چک میکنم سرور خارج عمدتا بعد بالارفتن پینگ os error 110 رو میده. 
اگر از systemd برای ریستارت استفاده کنم اختلالی پیش نمیاد؟ میتونید یه نمونه ازش بگید ؟

**Comment by Azumi67** [comment]
سلام. os error 110 توی کانتکست timed out ها فکر کنم هست و مشکل به خاطر اون هست. اتفاقا کسی دیگه هم بررسی کردم و دیدم کرون کار میکنه و من خودمم دارم استفاده میکنم. شما از طریق systemctl status servicename میتونید Interval ریست تایم ها رو ببینید . مثلا اگر 30 دقیقه گذاشتید ببینید که سر 30 دقیقه برای شما ریست میشه یا نه . جای سرویس نیم هم که نام سرویس مورد نظر رو باید بذارید.
مورد دیگه اینکه اگر ریست میکرد و باز هم این بود، میتونید بدون No delay تست کنید و برعکس
اگر اینها رو بررسی کردید و اطمینان پیدا کردید که مشکل دارید یک نمونه از ریست systemd هم به شما میگم اما کرون خودش اینکار رو میکنه . شما 30 دقیقه بذارید و بررسی کنید status رو و ببینید ریست میکنه یا نه.
به هر حال میتونه تایم اوت در سرور شما هم باشه که چنین خطایی هم گرفتید. سعی کنید optimizer هم نصب کنید و همینجا اطلاع دهید.
