### ISSUE TITLE
فراخوانی سرویس

### ISSUE THREAD

**Issue by arian2240** [Azumi67/Rathole_reverseTunnel#5]
با سلام با چه دستوری میتوان بدون نصب و کامپایل مجدد سرویس را فراخوانی و مدیریت کرد چون هردفعه اسکرپیت میزنیم از اول کامپایل میشه و خیلی طولانی و طاقت فرساست

**Comment by Azumi67** [comment]
سلام. خب دو تا اسکریپت برای نصب و اجرا هست. شما که نصب کردید فقط کافیه که اسکریپت تانل را استفاده کنید. مثلا این
`
sudo apt install curl -y && bash <(curl -s https://raw.githubusercontent.com/Azumi67/Rathole_reverseTunnel/main/go.sh)
`

یا 
`rm rat.go
sudo apt install wget -y && wget https://raw.githubusercontent.com/Azumi67/Rathole_reverseTunnel/main/rat.go && go run rat.go`
