### ISSUE TITLE
پورت مشابه

### ISSUE THREAD

**Issue by Amirmmh** [Azumi67/Rathole_reverseTunnel#6]
ببخشید میخواستم بدونم روی دوتا سرور خارج وقتی میزنم،حتما پورت کانفیگ ها باید فرق داشته باشه؟

چون روی پورت های مشابه زدم و کار نکرد متاسفانه و ارور eof داد کانفیگ
آیا باند پورت تانل داخل سرور خارج دوم متفاوت باشه یا اصلا در هر صورت کار نمیکنه

**Comment by Azumi67** [comment]
سلام. پورت تانل همونه. شما باید پورت کانفیگ را برای هر سرور خارج متفاوت بدید

**Comment by Amirmmh** [comment]
باشه پس خیلی ممنونم
نمیشه دوتا پورت متفاوت برای تانل هرکدوم از خارج ها بدم ولی پورت کانفیگا یکسان باشه؟

**Comment by Azumi67** [comment]
باز هم چون اون پورت در سرور ایران درگیر هست، خطای end of file را میگیرید.

**Comment by Amirmmh** [comment]
خب اوکیه متشکرم ♥️
