### ISSUE TITLE
ریست دستی

### ISSUE THREAD

**Issue by Mostafa-kaveh** [Azumi67/Rathole_reverseTunnel#7]
سلام وقت بخیر خسته نباشید
من یه مشکلی دارم هر روش تانلی که معرفی کردید انجام میدم بعد از مدتی قطع میشن و باید دستی اسکریپت رو اجرا کنم و ری استارت رو بزنم
ممنون میشم راهنمایی بفرمایید
حتی ریست تایمر هم ساعت های مختلف تنظیم کردم ولی باز مشکل دارم

**Comment by Azumi67** [comment]
سلام نمیشه اینطوری گفت.

**Comment by Azumi67** [comment]
سلام . اینطوری نمیشه گفت .  داخل crontab -e برید و ببینید دستورات اونجا هست یا خیر. سپس داخل
 journalctl -u نام سرویس.service 
برید و ببینید چه لاگ هایی داره و آیا ریست کرده یا نه . با دستور tail هم صحت اجرا شدن کرون رو بررسی کنید . 
ممکنه هم حتی دلیل دیگه ای داشته باشه . اینکه روی همه مشکل دارید ممکنه یه خاطر مشکل دیگری باشه
